### ISSUE TITLE
runtime: marked free object in span ...

### ISSUE THREAD

**Issue by danderson** [inetaf/netaddr#59]
Ran the netaddr benchmarks to test a change, with `go test -bench=. -count=5`. Partway through, the benchmark crashed and reported a pointer to a freed object:

```
runtime: marked free object in span 0x7fc17c424910, elemsize=32 freeindex=0 (bad use of unsafe.Pointer? try -d=checkptr)
0xc000136000 alloc marked  
0xc000136020 free  unmarked
0xc000136040 alloc marked  
0xc000136060 alloc marked  
0xc000136080 free  marked   zombie
000000c000136080:  0000000000582bc0  000000c00043a000 
000000c000136090:  00000000000c5eb0  0000000000000000 
0xc0001360a0 free  unmarked
0xc0001360c0 free  unmarked
0xc0001360e0 free  unmarked
0xc000136100 free  unmarked
0xc000136120 free  unmarked
0xc000136140 free  unmarked
0xc000136160 free  unmarked
0xc000136180 free  unmarked
0xc0001361a0 free  unmarked
0xc0001361c0 free  unmarked
0xc0001361e0 free  unmarked
0xc000136200 free  unmarked
0xc000136220 alloc marked  
0xc000136240 free  unmarked
0xc000136260 free  unmarked
0xc000136280 free  unmarked
0xc0001362a0 free  unmarked
0xc0001362c0 free  unmarked
0xc0001362e0 free  unmarked
0xc000136300 free  unmarked
0xc000136320 free  unmarked
0xc000136340 free  unmarked
0xc000136360 free  unmarked
0xc000136380 free  unmarked
0xc0001363a0 free  unmarked
0xc0001363c0 free  unmarked
0xc0001363e0 free  unmarked
0xc000136400 free  unmarked
0xc000136420 free  unmarked
0xc000136440 free  unmarked
0xc000136460 free  unmarked
0xc000136480 free  unmarked
0xc0001364a0 free  unmarked
0xc0001364c0 free  unmarked
0xc0001364e0 free  unmarked
0xc000136500 free  unmarked
0xc000136520 free  unmarked
0xc000136540 free  unmarked
0xc000136560 free  unmarked
0xc000136580 free  unmarked
0xc0001365a0 free  unmarked
0xc0001365c0 free  unmarked
0xc0001365e0 free  unmarked
0xc000136600 free  unmarked
0xc000136620 free  unmarked
0xc000136640 free  unmarked
0xc000136660 free  unmarked
0xc000136680 free  unmarked
0xc0001366a0 free  unmarked
0xc0001366c0 free  unmarked
0xc0001366e0 free  unmarked
0xc000136700 free  unmarked
0xc000136720 free  unmarked
0xc000136740 free  unmarked
0xc000136760 free  unmarked
0xc000136780 free  unmarked
0xc0001367a0 free  unmarked
0xc0001367c0 free  unmarked
0xc0001367e0 free  unmarked
0xc000136800 free  unmarked
0xc000136820 free  unmarked
0xc000136840 free  unmarked
0xc000136860 free  unmarked
0xc000136880 free  unmarked
0xc0001368a0 free  unmarked
0xc0001368c0 free  unmarked
0xc0001368e0 free  unmarked
0xc000136900 free  unmarked
0xc000136920 free  unmarked
0xc000136940 free  unmarked
0xc000136960 free  unmarked
0xc000136980 free  unmarked
0xc0001369a0 free  unmarked
0xc0001369c0 free  unmarked
0xc0001369e0 free  unmarked
0xc000136a00 free  unmarked
0xc000136a20 free  unmarked
0xc000136a40 free  unmarked
0xc000136a60 free  unmarked
0xc000136a80 free  unmarked
0xc000136aa0 free  unmarked
0xc000136ac0 free  unmarked
0xc000136ae0 free  unmarked
0xc000136b00 free  unmarked
0xc000136b20 free  unmarked
0xc000136b40 free  unmarked
0xc000136b60 free  unmarked
0xc000136b80 free  unmarked
0xc000136ba0 free  unmarked
0xc000136bc0 free  unmarked
0xc000136be0 free  unmarked
0xc000136c00 free  unmarked
0xc000136c20 free  unmarked
0xc000136c40 free  unmarked
0xc000136c60 free  unmarked
0xc000136c80 free  unmarked
0xc000136ca0 free  unmarked
0xc000136cc0 free  unmarked
0xc000136ce0 free  unmarked
0xc000136d00 free  unmarked
0xc000136d20 free  unmarked
0xc000136d40 free  unmarked
0xc000136d60 free  unmarked
0xc000136d80 free  unmarked
0xc000136da0 free  unmarked
0xc000136dc0 free  unmarked
0xc000136de0 free  unmarked
0xc000136e00 free  unmarked
0xc000136e20 free  unmarked
0xc000136e40 free  unmarked
0xc000136e60 free  unmarked
0xc000136e80 free  unmarked
0xc000136ea0 free  unmarked
0xc000136ec0 free  unmarked
0xc000136ee0 free  unmarked
0xc000136f00 free  unmarked
0xc000136f20 free  unmarked
0xc000136f40 free  unmarked
0xc000136f60 free  unmarked
0xc000136f80 free  unmarked
0xc000136fa0 free  unmarked
0xc000136fc0 free  unmarked
0xc000136fe0 free  unmarked
0xc000137000 free  unmarked
0xc000137020 free  unmarked
0xc000137040 free  unmarked
0xc000137060 free  unmarked
0xc000137080 free  unmarked
0xc0001370a0 free  unmarked
0xc0001370c0 free  unmarked
0xc0001370e0 alloc marked  
0xc000137100 free  unmarked
0xc000137120 free  unmarked
0xc000137140 free  unmarked
0xc000137160 free  unmarked
0xc000137180 free  unmarked
0xc0001371a0 free  unmarked
0xc0001371c0 free  unmarked
0xc0001371e0 free  unmarked
0xc000137200 free  unmarked
0xc000137220 free  unmarked
0xc000137240 free  unmarked
0xc000137260 free  unmarked
0xc000137280 free  unmarked
0xc0001372a0 free  unmarked
0xc0001372c0 free  unmarked
0xc0001372e0 free  unmarked
0xc000137300 free  unmarked
0xc000137320 free  unmarked
0xc000137340 free  unmarked
0xc000137360 free  unmarked
0xc000137380 free  unmarked
0xc0001373a0 free  unmarked
0xc0001373c0 free  unmarked
0xc0001373e0 free  unmarked
0xc000137400 free  unmarked
0xc000137420 free  unmarked
0xc000137440 free  unmarked
0xc000137460 free  unmarked
0xc000137480 free  unmarked
0xc0001374a0 free  unmarked
0xc0001374c0 free  unmarked
0xc0001374e0 free  unmarked
0xc000137500 free  unmarked
0xc000137520 free  unmarked
0xc000137540 free  unmarked
0xc000137560 free  unmarked
0xc000137580 free  unmarked
0xc0001375a0 free  unmarked
0xc0001375c0 free  unmarked
0xc0001375e0 free  unmarked
0xc000137600 free  unmarked
0xc000137620 free  unmarked
0xc000137640 free  unmarked
0xc000137660 free  unmarked
0xc000137680 free  unmarked
0xc0001376a0 free  unmarked
0xc0001376c0 free  unmarked
0xc0001376e0 free  unmarked
0xc000137700 free  unmarked
0xc000137720 free  unmarked
0xc000137740 free  unmarked
0xc000137760 free  unmarked
0xc000137780 free  unmarked
0xc0001377a0 free  unmarked
0xc0001377c0 free  unmarked
0xc0001377e0 free  unmarked
0xc000137800 free  unmarked
0xc000137820 free  unmarked
0xc000137840 free  unmarked
0xc000137860 free  unmarked
0xc000137880 free  unmarked
0xc0001378a0 free  unmarked
0xc0001378c0 free  unmarked
0xc0001378e0 free  unmarked
0xc000137900 free  unmarked
0xc000137920 free  unmarked
0xc000137940 free  unmarked
0xc000137960 free  unmarked
0xc000137980 free  unmarked
0xc0001379a0 free  unmarked
0xc0001379c0 free  unmarked
0xc0001379e0 free  unmarked
0xc000137a00 free  unmarked
0xc000137a20 free  unmarked
0xc000137a40 free  unmarked
0xc000137a60 free  unmarked
0xc000137a80 free  unmarked
0xc000137aa0 free  unmarked
0xc000137ac0 free  unmarked
0xc000137ae0 free  unmarked
0xc000137b00 free  unmarked
0xc000137b20 free  unmarked
0xc000137b40 free  unmarked
0xc000137b60 free  unmarked
0xc000137b80 free  unmarked
0xc000137ba0 free  unmarked
0xc000137bc0 free  unmarked
0xc000137be0 free  unmarked
0xc000137c00 free  unmarked
0xc000137c20 free  unmarked
0xc000137c40 free  unmarked
0xc000137c60 free  unmarked
0xc000137c80 free  unmarked
0xc000137ca0 free  unmarked
0xc000137cc0 free  unmarked
0xc000137ce0 free  unmarked
0xc000137d00 free  unmarked
0xc000137d20 free  unmarked
0xc000137d40 free  unmarked
0xc000137d60 free  unmarked
0xc000137d80 free  unmarked
0xc000137da0 free  unmarked
0xc000137dc0 free  unmarked
0xc000137de0 free  unmarked
0xc000137e00 free  unmarked
0xc000137e20 free  unmarked
0xc000137e40 free  unmarked
0xc000137e60 free  unmarked
0xc000137e80 free  unmarked
0xc000137ea0 free  unmarked
0xc000137ec0 free  unmarked
0xc000137ee0 free  unmarked
0xc000137f00 free  unmarked
0xc000137f20 free  unmarked
0xc000137f40 free  unmarked
0xc000137f60 free  unmarked
0xc000137f80 free  unmarked
0xc000137fa0 free  unmarked
0xc000137fc0 free  unmarked
0xc000137fe0 free  unmarked
fatal error: found pointer to free object

runtime stack:
runtime.SetFinalizer.func1()
	/nix/store/whf767pjnhyllfk1jkma1rg4np2dizcc-go-1.15.5/share/go/src/runtime/mfinal.go:369 +0x2e

goroutine 960 [running]:
runtime.systemstack_switch()
	/nix/store/whf767pjnhyllfk1jkma1rg4np2dizcc-go-1.15.5/share/go/src/runtime/asm_amd64.s:330 fp=0xc000069c00 sp=0xc000069bf8 pc=0x46a700
runtime.SetFinalizer(0x589b20, 0xc000136080, 0x0, 0x0)
	/nix/store/whf767pjnhyllfk1jkma1rg4np2dizcc-go-1.15.5/share/go/src/runtime/mfinal.go:368 +0x465 fp=0xc000069ce8 sp=0xc000069c00 pc=0x419da5
go4.org/intern.Get(0x582bc0, 0xc0005ac050, 0x0)
	/home/dave/.local/go.path/pkg/mod/go4.org/intern@v0.0.0-20201222181806-763bd24e33ab/intern.go:69 +0x185 fp=0xc000069d60 sp=0xc000069ce8 pc=0x52a025
inet.af/netaddr.IP.WithZone(0x80fe, 0xe1c29f118c3ec01c, 0xc000136060, 0x5bee97, 0x5, 0x0, 0x0, 0x0)
	/home/dave/hack/netaddr/netaddr.go:356 +0xce fp=0xc000069da0 sp=0xc000069d60 pc=0x5459ae
inet.af/netaddr.ParseIP(0x5bee7d, 0x1f, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/dave/hack/netaddr/netaddr.go:190 +0x1fb fp=0xc000069e98 sp=0xc000069da0 pc=0x54483b
inet.af/netaddr.BenchmarkParseIPv6(0xc0000aa480)
	/home/dave/hack/netaddr/netaddr_test.go:1225 +0x4b fp=0xc000069ee8 sp=0xc000069e98 pc=0x556e8b
testing.(*B).runN(0xc0000aa480, 0x1be7ac)
	/nix/store/whf767pjnhyllfk1jkma1rg4np2dizcc-go-1.15.5/share/go/src/testing/benchmark.go:191 +0xeb fp=0xc000069f58 sp=0xc000069ee8 pc=0x4da7eb
testing.(*B).launch(0xc0000aa480)
	/nix/store/whf767pjnhyllfk1jkma1rg4np2dizcc-go-1.15.5/share/go/src/testing/benchmark.go:321 +0xea fp=0xc000069fd8 sp=0xc000069f58 pc=0x4daeaa
runtime.goexit()
	/nix/store/whf767pjnhyllfk1jkma1rg4np2dizcc-go-1.15.5/share/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000069fe0 sp=0xc000069fd8 pc=0x46c4e1
created by testing.(*B).doBench
	/nix/store/whf767pjnhyllfk1jkma1rg4np2dizcc-go-1.15.5/share/go/src/testing/benchmark.go:276 +0x55

goroutine 1 [chan receive]:
testing.(*B).doBench(0xc0000aa480, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/nix/store/whf767pjnhyllfk1jkma1rg4np2dizcc-go-1.15.5/share/go/src/testing/benchmark.go:277 +0x73
testing.(*benchContext).processBench(0xc0000e8040, 0xc0000aa480)
	/nix/store/whf767pjnhyllfk1jkma1rg4np2dizcc-go-1.15.5/share/go/src/testing/benchmark.go:572 +0x226
testing.(*B).run(0xc0000aa480)
	/nix/store/whf767pjnhyllfk1jkma1rg4np2dizcc-go-1.15.5/share/go/src/testing/benchmark.go:268 +0x65
testing.(*B).Run(0xc0000aa240, 0x5baeb2, 0x12, 0x5c4308, 0x4da400)
	/nix/store/whf767pjnhyllfk1jkma1rg4np2dizcc-go-1.15.5/share/go/src/testing/benchmark.go:657 +0x42f
testing.runBenchmarks.func1(0xc0000aa240)
	/nix/store/whf767pjnhyllfk1jkma1rg4np2dizcc-go-1.15.5/share/go/src/testing/benchmark.go:533 +0x78
testing.(*B).runN(0xc0000aa240, 0x1)
	/nix/store/whf767pjnhyllfk1jkma1rg4np2dizcc-go-1.15.5/share/go/src/testing/benchmark.go:191 +0xeb
testing.runBenchmarks(0x5ba1b6, 0xf, 0xc0000e8020, 0x6d3b40, 0xc, 0xc, 0x6d7d20)
	/nix/store/whf767pjnhyllfk1jkma1rg4np2dizcc-go-1.15.5/share/go/src/testing/benchmark.go:542 +0x3d1
testing.(*M).Run(0xc000154000, 0x0)
	/nix/store/whf767pjnhyllfk1jkma1rg4np2dizcc-go-1.15.5/share/go/src/testing/testing.go:1351 +0x51d
main.main()
	_testmain.go:137 +0x138
```

cc @bradfitz @josharian, looks like there's a race/bug in the implementation of intern?

**Comment by josharian** [comment]
Well, grawlix. Must be.

**Comment by danderson** [comment]
The crash says so, but for the record, this is Go 1.15.5.

**Comment by danderson** [comment]
The crashy benchmark is BenchmarkParseIPv6, which unsurprisingly creates and drops v6-with-zone addrs in a tight loop, with the same zone value each time. The crash occurs promptly in the first pass through the benchmark. Going to see if I can add a crasher torture test to go4.org/intern and repro there.

**Comment by danderson** [comment]
Can repro with a simple case in go4.org/intern. Filed https://github.com/go4org/intern/issues/2.

**Comment by josharian** [comment]
Excellent, thank you! (But aren't you on vacation?)

**Comment by danderson** [comment]
I am! Optimizing netaddr is something I've been wanting to do for a while, and I felt like writing code :) Unfortunately, with this bug, I can't run benchmarks, and I don't think I'm smart enough to figure out the bug :(

**Comment by josharian** [comment]
If you want to not be blocked, eliminate the runtime.SetFinalizer calls in intern and the crashes should go away. It’ll leak memory, but that’s ok.

However, this does raise the question of how fixable the bug is, and whether it puts the viability of the current code into question. My first suspicion is, of course, that the bug is the theoretical one I outlined in my long comment. If that is the case, it won’t be fixed until 1.17 at the very earliest. Are we willing to leak zones until a fix can be found? Or do we need to seek an alternative approach?

P.S. I recommend grabbing my fuzz function and running it as you optimize; it’s good at finding regressions quickly.

**Comment by josharian** [comment]
Actually, it isn’t enough to remove the SetFinalizer calls; you’d also need to make the map a map[interface{}]*Value, and remove all unsafe. What a mess. We should make a safe version of package intern with the same api, behind a build tag. Then people can use that if they suspect a package intern bug.

**Comment by danderson** [comment]
Having a flag-flippable version of the package that grows without bounds doesn't seem super useful outside of specific cases, because "choose between a resource DoS or a crash DoS" doesn't sound like a great choice - but I'm willing to be overruled on that.

How fixable the bug is - I guess question 1 would be: what is the bug? Is it a race as you described between the finalizer being scheduled and a new reference being created? Why are we the first to run into it, if so? Oh, I suppose because materializing a reference to a GCable object is normally impossible, but we're combining unsafe and SetFinalizer, two individually dangerous things. Grump.

I don't have other ideas for how to get these semantics. I briefly thought we could SetFinalizer on each netaddr.IP and do manual refcounting, but IP is a value type so that won't work. AFAICT, we really need runtime+GC support for weakrefs if this is going to work safely, no?

**Comment by josharian** [comment]
> Having a flag-flippable version of the package that grows without bounds doesn't seem super useful

agreed. It’s purpose is for moments like this—to confirm that the bug is in package intern and to provide a temporary workaround if so.

> materializing a reference to a GCable object is normally impossible

exactly.

> we really need runtime+GC support for weakrefs

That would be ideal. Although maybe there is a way to make this work yet.

**Comment by bradfitz** [comment]
Well, I can reproduce trivially. For better or worse. (worst: we should've caught this much earlier)

And I can confirm that changing go4.org/intern's `valMap` into type `map[interface{}]unsafe.Pointer` fixes the problem. (but being leaky)

**Comment by danderson** [comment]
Added some discussion/questions in https://github.com/go4org/intern/issues/2, FYI (not sure if people are subscribed to go4.org/intern yet). Also happy to bow out and let Go compiler grown-ups think about it :)
